server:
  port: 8080

spring:
  application:
    name: api-service

  datasource:
    url: jdbc:postgresql://localhost:5432/codepulse_api
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html