server:
  port: 8081

spring:
  application:
    name: scheduler-service

api-service:
  base-url: http://localhost:8080

worker-service:
  base-url: http://localhost:8082

scheduler:
  fixed-delay: 60000

rest-client:
  connect-timeout: 5000
  read-timeout: 30000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
